// Benchmarks for the new sudoku:: engine.
// Mirrors the style of the per-engine *Benchmark.h files so option 6's
// solving comparison can plug it in.

#ifndef SUDOKU_BENCHMARK_H_
#define SUDOKU_BENCHMARK_H_

#include <chrono>
#include <cstdint>
#include <iostream>

#include "Sudoku.h"
#include "SudokuEngine.h"   // for SudokuGameEngine::DifficultyLevel only

namespace sudoku_bench
{
    inline sudoku::Generator<3>::Difficulty mapDifficulty(SudokuGameEngine::DifficultyLevel d)
    {
        using Old = SudokuGameEngine::DifficultyLevel;
        using New = sudoku::Generator<3>::Difficulty;
        switch (d)
        {
            case Old::VeryEasy: return New::VeryEasy;
            case Old::Easy:     return New::Easy;
            case Old::Medium:   return New::Medium;
            case Old::Hard:     return New::Hard;
            case Old::VeryHard: return New::VeryHard;
        }
        return New::Medium;
    }

    inline long long benchmarkCombinationGeneration(
        unsigned int iterationsPerLoop,
        unsigned int loops = 1)
    {
        sudoku::Generator<3> gen;
        sudoku::Board<3> sink;

        std::cout << "Sudoku Engine NEW (sudoku::) Combination Generation Benchmark Started\n\n"
                  << "Iterations per loop: " << iterationsPerLoop << "\n"
                  << "Loops: " << loops << "\n\n";

        auto totalStart = std::chrono::high_resolution_clock::now();
        for (unsigned int loop = 1; loop <= loops; ++loop)
        {
            std::cout << "Running loop #" << loop << " ... ";
            auto loopStart = std::chrono::high_resolution_clock::now();
            for (unsigned int i = 0; i < iterationsPerLoop; ++i)
            {
                // Full board has no hidden cells.
                auto p = gen.generate(sudoku::Generator<3>::Difficulty::VeryEasy);
                sink = p.solution;  // keep the optimizer from eliding the call
            }
            auto loopEnd = std::chrono::high_resolution_clock::now();
            auto loopElapsed = std::chrono::duration_cast<std::chrono::microseconds>(loopEnd - loopStart).count();
            std::cout << "loop finished in " << loopElapsed << " microseconds\n";
        }
        auto totalEnd = std::chrono::high_resolution_clock::now();
        auto totalElapsed = std::chrono::duration_cast<std::chrono::microseconds>(totalEnd - totalStart).count();
        std::cout << "\n" << iterationsPerLoop * loops << " iterations finished in "
                  << totalElapsed << " microseconds (" << (totalElapsed / 1000000.0) << " seconds)\n\n";
        (void)sink;
        return totalElapsed;
    }

    inline long long benchmarkGameGeneration(
        SudokuGameEngine::DifficultyLevel difficulty,
        unsigned int iterationsPerLoop,
        unsigned int loops = 1)
    {
        sudoku::Generator<3> gen;
        sudoku::Board<3> sink;

        std::cout << "Sudoku Engine NEW (sudoku::) Game Generation Benchmark Started\n\n"
                  << "Difficulty level: " << difficulty << "\n"
                  << "Iterations per loop: " << iterationsPerLoop << "\n"
                  << "Loops: " << loops << "\n\n";

        auto totalStart = std::chrono::high_resolution_clock::now();
        for (unsigned int loop = 1; loop <= loops; ++loop)
        {
            std::cout << "Running loop #" << loop << " ... ";
            auto loopStart = std::chrono::high_resolution_clock::now();
            for (unsigned int i = 0; i < iterationsPerLoop; ++i)
            {
                auto p = gen.generate(mapDifficulty(difficulty));
                sink = p.givens;
            }
            auto loopEnd = std::chrono::high_resolution_clock::now();
            auto loopElapsed = std::chrono::duration_cast<std::chrono::microseconds>(loopEnd - loopStart).count();
            std::cout << "loop finished in " << loopElapsed << " microseconds\n";
        }
        auto totalEnd = std::chrono::high_resolution_clock::now();
        auto totalElapsed = std::chrono::duration_cast<std::chrono::microseconds>(totalEnd - totalStart).count();
        std::cout << "\n" << iterationsPerLoop * loops << " iterations finished in "
                  << totalElapsed << " microseconds (" << (totalElapsed / 1000000.0) << " seconds)\n\n";
        (void)sink;
        return totalElapsed;
    }

    inline long long benchmarkGameSolving(
        SudokuGameEngine::DifficultyLevel difficulty,
        unsigned int iterationsPerLoop,
        unsigned int loops = 1)
    {
        // Mirror the existing per-engine benchmark: one puzzle per loop, solve
        // it `iterationsPerLoop` times. Source puzzle is generated by the same
        // engine (parity with how the other benchmark files do it).
        sudoku::Generator<3> gen;
        sudoku::Solver<3>    solver;
        long long totalElapsedMicros = 0;

        std::cout << "Sudoku Engine NEW (sudoku::) Game Solving Benchmark Started\n\n"
                  << "Difficulty level: " << difficulty << "\n"
                  << "Iterations per loop: " << iterationsPerLoop << "\n"
                  << "Loops: " << loops << "\n\n";

        for (unsigned int loop = 1; loop <= loops; ++loop)
        {
            const auto puzzle = gen.generate(mapDifficulty(difficulty));

            std::cout << "Running loop #" << loop << " ... ";
            auto loopStart = std::chrono::high_resolution_clock::now();
            for (unsigned int i = 0; i < iterationsPerLoop; ++i)
            {
                const auto r = solver.solve(puzzle.givens);
                (void)r;
            }
            auto loopEnd = std::chrono::high_resolution_clock::now();
            auto loopElapsed = std::chrono::duration_cast<std::chrono::microseconds>(loopEnd - loopStart).count();
            totalElapsedMicros += loopElapsed;
            std::cout << "loop finished in " << loopElapsed << " microseconds\n";
        }
        std::cout << "\n" << iterationsPerLoop * loops << " iterations finished in "
                  << totalElapsedMicros << " microseconds (" << (totalElapsedMicros / 1000000.0) << " seconds)\n\n";
        return totalElapsedMicros;
    }
}

#endif
