// Stress / percentile benchmark: original SudokuEngine vs new sudoku:: solver.
//
// Puzzles are pre-generated by the original SudokuEngine (the source of
// truth), then each engine solves each puzzle solvesPerPuzzle times.
// Per-solve nanosecond timings are collected and reduced to avg + percentiles.

#ifndef SUDOKU_STRESS_TEST_H_
#define SUDOKU_STRESS_TEST_H_

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <vector>

#include "Sudoku.h"
#include "SudokuBenchmark.h"  // for sudoku_bench::mapDifficulty
#include "SudokuEngine.h"
#include "SudokuTest.h"   // for read/write helpers

namespace sudoku_stress
{
    struct Stats
    {
        long long avgNs;
        long long p50Ns;
        long long p95Ns;
        long long p99Ns;
        long long p999Ns;
        long long p9999Ns;
        long long minNs;
        long long maxNs;
        long long totalNs;
        std::size_t count;
    };

    inline long long percentile(const std::vector<long long>& sorted, double p)
    {
        if (sorted.empty()) return 0;
        std::size_t idx = static_cast<std::size_t>(p * sorted.size());
        if (idx >= sorted.size()) idx = sorted.size() - 1;
        return sorted[idx];
    }

    inline Stats compute(std::vector<long long>& samples)
    {
        Stats s{};
        s.count = samples.size();
        if (samples.empty()) return s;
        std::sort(samples.begin(), samples.end());
        long long sum = 0;
        for (long long v : samples) sum += v;
        s.totalNs = sum;
        s.avgNs   = sum / static_cast<long long>(samples.size());
        s.minNs   = samples.front();
        s.maxNs   = samples.back();
        s.p50Ns   = percentile(samples, 0.50);
        s.p95Ns   = percentile(samples, 0.95);
        s.p99Ns   = percentile(samples, 0.99);
        s.p999Ns  = percentile(samples, 0.999);
        s.p9999Ns = percentile(samples, 0.9999);
        return s;
    }

    inline void printStats(const char* label, const Stats& s)
    {
        auto us = [](long long ns) { return ns / 1000.0; };
        std::cout << "  [" << label << "]\n"
                  << "    samples : " << s.count << "\n"
                  << "    total   : " << us(s.totalNs) << " us\n"
                  << "    min     : " << us(s.minNs)   << " us\n"
                  << "    avg     : " << us(s.avgNs)   << " us\n"
                  << "    p50     : " << us(s.p50Ns)   << " us\n"
                  << "    p95     : " << us(s.p95Ns)   << " us\n"
                  << "    p99     : " << us(s.p99Ns)   << " us\n"
                  << "    p999    : " << us(s.p999Ns)  << " us\n"
                  << "    p9999   : " << us(s.p9999Ns) << " us\n"
                  << "    max     : " << us(s.maxNs)   << " us\n";
    }

    inline void printRatio(const char* what, long long orig, long long neu)
    {
        if (orig <= 0 || neu <= 0) return;
        const double r = static_cast<double>(orig) / static_cast<double>(neu);
        std::cout << "    " << std::left << std::setw(7) << what
                  << ": Original " << (orig / 1000.0) << " us  /  "
                  << "New " << (neu / 1000.0) << " us  =  "
                  << std::fixed << std::setprecision(3) << r << "x ";
        std::cout << (r >= 1.0 ? "(new faster)" : "(original faster)")
                  << std::defaultfloat << "\n";
    }

    inline void runVeryHardComparison(int numPuzzles, int solvesPerPuzzle)
    {
        using OldEngine = SudokuGameEngine::SudokuEngine<unsigned char, unsigned char, 3>;
        const auto difficulty = SudokuGameEngine::DifficultyLevel::VeryHard;

        std::cout << "\n========== STRESS TEST: Original vs New (Very Hard) ==========\n"
                  << "Puzzles:           " << numPuzzles << "\n"
                  << "Solves per puzzle: " << solvesPerPuzzle << "\n"
                  << "Total solves:      " << (long long)numPuzzles * solvesPerPuzzle
                  << " per engine\n\n";

        // -------- Stage 1: pre-generate puzzle set with the new generator -----
        // The new sudoku::Generator is the source of test cases here. It's
        // ~180x faster than the original engine's generator while producing
        // puzzles that have been cross-validated against the original (see
        // checkCrossValidationMedium in SudokuTest.h).
        std::cout << "Generating " << numPuzzles << " Very Hard puzzles with sudoku::Generator...\n  " << std::flush;
        std::vector<sudoku::Board<3>> puzzles;
        puzzles.reserve(numPuzzles);
        sudoku::Generator<3> gen;
        const auto newDifficulty = sudoku_bench::mapDifficulty(difficulty);
        auto genStart = std::chrono::high_resolution_clock::now();
        // Print a tick every ~5% of the way through (or every 1000, whichever is larger).
        const int genTick = std::max(1000, numPuzzles / 20);
        for (int i = 0; i < numPuzzles; ++i)
        {
            const auto p = gen.generate(newDifficulty);
            puzzles.push_back(p.givens);
            if ((i + 1) % genTick == 0)
            {
                std::cout << "." << std::flush;
            }
        }
        auto genEnd = std::chrono::high_resolution_clock::now();
        const long long genUs = std::chrono::duration_cast<std::chrono::milliseconds>(genEnd - genStart).count();
        std::cout << "\n  done in " << genUs << " ms.\n\n";

        // -------- Stage 2: measure original engine ---------------------------
        std::vector<long long> origSamples;
        origSamples.reserve(static_cast<std::size_t>(numPuzzles) * solvesPerPuzzle);
        {
            OldEngine orig;
            // Warm-up: solve every puzzle once, untimed.
            for (const auto& b : puzzles)
            {
                sudoku_test::writePuzzleToOld(orig, b);
                orig.trySolve();
            }
            std::cout << "Timing Original engine...\n  " << std::flush;
            auto t0 = std::chrono::high_resolution_clock::now();
            for (int rep = 0; rep < solvesPerPuzzle; ++rep)
            {
                for (const auto& b : puzzles)
                {
                    auto a = std::chrono::high_resolution_clock::now();
                    sudoku_test::writePuzzleToOld(orig, b);
                    orig.trySolve();
                    auto z = std::chrono::high_resolution_clock::now();
                    origSamples.push_back(
                        std::chrono::duration_cast<std::chrono::nanoseconds>(z - a).count());
                }
                std::cout << "." << std::flush;
            }
            auto t1 = std::chrono::high_resolution_clock::now();
            std::cout << "\n  done in "
                      << std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count()
                      << " ms.\n";
        }

        // -------- Stage 3: measure new sudoku:: engine -----------------------
        std::vector<long long> newSamples;
        newSamples.reserve(static_cast<std::size_t>(numPuzzles) * solvesPerPuzzle);
        {
            sudoku::Solver<3> solver;
            // Warm-up.
            for (const auto& b : puzzles)
            {
                volatile auto r = solver.solve(b);
                (void)r;
            }
            std::cout << "Timing New engine.......\n  " << std::flush;
            auto t0 = std::chrono::high_resolution_clock::now();
            for (int rep = 0; rep < solvesPerPuzzle; ++rep)
            {
                for (const auto& b : puzzles)
                {
                    auto a = std::chrono::high_resolution_clock::now();
                    volatile auto r = solver.solve(b);
                    (void)r;
                    auto z = std::chrono::high_resolution_clock::now();
                    newSamples.push_back(
                        std::chrono::duration_cast<std::chrono::nanoseconds>(z - a).count());
                }
                std::cout << "." << std::flush;
            }
            auto t1 = std::chrono::high_resolution_clock::now();
            std::cout << "\n  done in "
                      << std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count()
                      << " ms.\n\n";
        }

        // -------- Stage 4: stats ---------------------------------------------
        const Stats origS = compute(origSamples);
        const Stats newS  = compute(newSamples);
        printStats("Original", origS);
        std::cout << "\n";
        printStats("New (sudoku::)", newS);

        std::cout << "\n  --- Original / New (ratio > 1 means New is faster) ---\n";
        printRatio("total",  origS.totalNs, newS.totalNs);
        printRatio("avg",    origS.avgNs,   newS.avgNs);
        printRatio("p50",    origS.p50Ns,   newS.p50Ns);
        printRatio("p95",    origS.p95Ns,   newS.p95Ns);
        printRatio("p99",    origS.p99Ns,   newS.p99Ns);
        printRatio("p999",   origS.p999Ns,  newS.p999Ns);
        printRatio("p9999",  origS.p9999Ns, newS.p9999Ns);
        printRatio("max",    origS.maxNs,   newS.maxNs);
        std::cout << "\n";
    }
}

#endif
